mj:
  discord:
    guild-id: 1123158769224929280
    channel-id: 1123158834744131615
    user-token: MTAxMjE1OTc4MjQ3NzY0Mzc5Nw.G24u3k.FLlf2coRtc9w_VVTK8ZM_Urg8L2nszSGDs5iWk
    session-id: 76d5bbda7010272be850b64457a095ab
    user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
    user-wss: true
  task-store:
    type: in_memory
    timeout: 30d
  translate-way: null
  queue:
    timeout-minutes: 10
    core-size: 5
    queue-size: 100
  notifyHook: http://localhost:8084/notifyHook